-- Run in Supabase SQL Editor

create table if not exists public.waitlist_signups (
    id bigint generated by default as identity primary key,
    email text not null unique,
    city text,
    consent boolean not null default false,
    source_form text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.waitlist_signups enable row level security;

-- Allow anonymous users (frontend with anon key) to insert or upsert.
drop policy if exists "anon_can_insert_waitlist" on public.waitlist_signups;
create policy "anon_can_insert_waitlist"
on public.waitlist_signups
for insert
to anon
with check (consent = true);

-- Allow authenticated users to insert too (optional, safe with same consent check).
drop policy if exists "authenticated_can_insert_waitlist" on public.waitlist_signups;
create policy "authenticated_can_insert_waitlist"
on public.waitlist_signups
for insert
to authenticated
with check (consent = true);

-- Block anon reads by default.
drop policy if exists "anon_no_read_waitlist" on public.waitlist_signups;
create policy "anon_no_read_waitlist"
on public.waitlist_signups
for select
to anon
using (false);
